-- Fix: refresh_dashboard_cache() fails in SQL Editor with "Authentication required".
--
-- STEP 1 — Run the full updated supabase/master_data_adoption.sql first
--         (creates _build_adoption_bundle and updates get_adoption_bundle).
--
-- STEP 2 — Run supabase/fix_refresh_cache_auth.sql
--         (updates refresh_dashboard_cache to call _build_adoption_bundle).
--
-- Or after step 1, you can simply run:
--   SELECT refresh_dashboard_cache();
